# Generated by Django 3.0 on 2020-04-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='author notes', max_length=250),
            preserve_default=False,
        ),
    ]
