# Generated by Django 3.0 on 2020-04-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_exchange_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='color', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='permanent_type',
            field=models.CharField(default='have to edit', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='pool',
            field=models.CharField(default='have to add', max_length=60),
            preserve_default=False,
        ),
    ]
