# Generated by Django 3.0 on 2020-04-30 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_exchange_app', '0002_auto_20200430_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('release_date', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_cards', to='mtg_exchange_app.Pool'),
        ),
    ]
