# Generated by Django 3.0 on 2020-05-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_exchange_app', '0003_auto_20200430_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_image'),
        ),
    ]
