# Generated by Django 3.0 on 2020-05-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_exchange_app', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity_ordered',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
