# Generated by Django 3.1.1 on 2020-09-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_exchange_app', '0006_auto_20200910_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='last_name',
        ),
    ]
