# Generated by Django 3.1.1 on 2020-09-10 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtg_exchange_app', '0007_auto_20200910_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='mtg_exchange_app.address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='card',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='mtg_exchange_app.card'),
            preserve_default=False,
        ),
    ]
