const express = require('express')
const cors = require('cors')
const app = express()
require('./config/mongoose.config')
app.use(cors())
app.use(express.json())
const piratesRoutesFunc = require('./routes/pirate.routes')
piratesRoutesFunc(app)
app.listen(8000, () => console.log('hey there from 8000'))

